Add addNewHouseData query function
GSG-G9/house-hunting-app pull request #103
Opened 2021-02-09 10:20 UTC by mAbadsa

Relates #28

**Add new house routes**

> This route is protected.

- [X] Create addNewHouseData query function.
- [ ] Create a validation schema by using the yup library.
- [ ] Create POST '/houses/' route.
- [ ] Create an addNewHouse controller function.

2021-02-09 16:10 UTC, AdhamHaisami commented on server/database/queries/house/addNewHousedata.js
> +      'INSERT INTO houses ( user_id, location_id, title, description, room_num, bathroom_num, category, price, area, image ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING *;',
you can replace params in the query with shortcuts. for example ($1, $2 ,$3 ....)

2021-02-09 16:11 UTC, AdhamHaisami submitted a review, later dismissed

2021-02-09 18:14 UTC, yasmeenattallah approved these changes

2021-02-10 08:06 UTC, yasmeenattallah approved these changes

2021-02-10 10:14 UTC, mariamisa approved these changes

2021-02-10 10:16 UTC, mariamisa requested changes
Solve conflicts

2021-02-10 12:04 UTC, merged