Search page
GSG-G9/house-hunting-app pull request #105
Opened 2021-02-09 11:55 UTC by yasmeenattallah

Relates #104
### Search Page : 
contain a search bar with advanced feature to allow user search by : 
- location
- rooms 
- categories 
- price 
when clicking on the search icon all available houses will display

2021-02-11 18:43 UTC, mAbadsa submitted a review, later dismissed

2021-02-12 03:31 UTC, mariamisa requested changes
make a clean function that removes all search values and handle loading status

2021-02-12 09:56 UTC, okjake commented on client/src/Pages/Houses/index.js
> +          ? house.description.includes(
Maybe double check that this is working correctly - it looks to me like there's a missing `)` before `||`, and it got put on line 61 instead

2021-02-12 09:56 UTC, okjake commented on client/src/Pages/Houses/index.js
> +      .filter((house) => (catagories ? house.category === catagories : true))
Typo `categories`

2021-02-12 10:01 UTC, okjake commented on client/src/Pages/Houses/index.js
> +        if (isCurrent) {
It took me a minute to figure this out - this is to prevent `setHouses` being called if the component was already unmounted?

2021-02-12 21:19 UTC, merged