Update House
GSG-G9/house-hunting-app pull request #150
Opened 2021-02-16 08:18 UTC by yasmeenattallah

Relates #30

2021-02-16 19:09 UTC, mariamisa requested changes

2021-02-16 19:09 UTC, mariamisa commented on server/controller/routes/house/updateHouse.js
> +    } = req.body;
you can pass the object req. body directly to the query, instead of distracting then  pass it

2021-02-16 19:09 UTC, mariamisa commented on server/database/config/build.sql
> +   DECIMAL(8,2),
why you delete the price?

2021-02-16 20:27 UTC, okjake commented on server/database/queries/house/updateHouse.js
> +    values: [
I think you need to double check these - the values don't match the placeholders. It looks OK until bathroom_num but looks like the ones after that were rearranged

2021-02-16 20:28 UTC, okjake commented
Looks good! Just a couple of small things

2021-02-17 16:55 UTC, mAbadsa approved these changes

2021-02-18 12:27 UTC, closed without merging