install eslint package and initialize it
GSG-G9/house-hunting-app pull request #43
Opened 2021-02-01 14:01 UTC by yasmeenattallah

Relate  #27 
install linter to check errors in the project

2021-02-01 16:33 UTC, mariamisa requested changes

2021-02-01 16:33 UTC, mariamisa commented on .travis.yml
> +  database: houseHunting
add a new line on the bottom

2021-02-01 19:01 UTC, yasmeenattallah commented on .travis.yml
> +  database: houseHunting
solved

2021-02-02 00:34 UTC, mariamisa approved these changes

2021-02-02 00:36 UTC, merged