Create Header Component
GSG-G9/house-hunting-app pull request #77
Opened 2021-02-03 15:53 UTC by mAbadsa

Relates #58
**Header Component.**
Create Header Component with links and titles.
1. Using Material-UI pre-built Component [ Container, Toolbar, Typography].
2. Using LinkItem #60  Component.
3. With CSS Styling.
4. We will use the Header component on every page.

2021-02-03 20:34 UTC, yasmeenattallah reviewed
why don't use prop-types

2021-02-04 08:16 UTC, yasmeenattallah reviewed
it's better to spread make a style in a style.js file

2021-02-04 10:55 UTC, AdhamHaisami submitted a review, later dismissed

2021-02-04 11:22 UTC, mariamisa requested changes
pull main

2021-02-04 11:22 UTC, mariamisa commented on client/src/Components/Navbar/style.js
> +const useStyles = makeStyles(() => ({
pass the theme as a parameter to your makeStyle function, then get color from the theme, palette
``` 
const useStyles = makeStyles((theme) => ({
```

2021-02-04 11:23 UTC, mariamisa requested changes

2021-02-04 11:23 UTC, mariamisa commented on client/src/Components/Navbar/index.js
> +              <LinkItem underline="none" text="Houses" linkUrl="/" />
get link Url value from ``` client/src/Utils/routes.constant.js file ```

2021-02-04 17:19 UTC, AdhamHaisami approved these changes

2021-02-04 19:06 UTC, AdhamHaisami submitted a review, later dismissed

2021-02-04 22:06 UTC, mariamisa approved these changes

2021-02-04 22:06 UTC, merged