Write logout route and logout controller
GSG-G9/house-hunting-app pull request #89
Opened 2021-02-05 18:40 UTC by mAbadsa

Relates #40

**Logout route**

1. In this branch, we build a logout process to clear auth token from the cookies.
2. This process consists of a logout route and a logout controller.
3. We use the Expressjs framework and use the pre-built Router method.

2021-02-06 13:30 UTC, yasmeenattallah submitted a review, later dismissed

2021-02-06 19:07 UTC, yasmeenattallah commented on server/controller/routes/user/logout.js
> +    return res
should you use async .. await

2021-02-07 07:40 UTC, AdhamHaisami submitted a review, later dismissed

2021-02-07 09:52 UTC, mariamisa requested changes

2021-02-07 09:52 UTC, mariamisa commented on server/router/index.js
delete this test route

2021-02-07 10:49 UTC, mariamisa requested changes

2021-02-07 10:49 UTC, mariamisa commented on server/controller/routes/user/index.js
> +const logout = require('./user/logout');
this path not true

2021-02-07 10:49 UTC, mariamisa commented on server/router/user.js
> +const { logout } = require('../controller/routes/user/index');
remove index from require

2021-02-07 11:43 UTC, mariamisa approved these changes

2021-02-07 11:43 UTC, merged